### ISSUE TITLE
Remote end closed connection without response

### ISSUE THREAD

**Issue by satybald** [StepicOrg/stepic-oauth2-videodownloader#1]
While downloading a video I get the following response. I guess it relates more to the server, than to the downloader.

```
python3 weekDownloader.py 253 1
Only video: 18
Downloading file  Video_0.mp4
Done
Downloading file  Video_1.mp4
Done
Downloading file  Video_2.mp4
Traceback (most recent call last):
  File "weekDownloader.py", line 76, in <module>
    main(sys.argv[1:])
  File "weekDownloader.py", line 70, in main
    urllib.request.urlretrieve(el, filename)
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 187, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 162, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 471, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 581, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 503, in error
    result = self._call_chain(*args)
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 443, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 686, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 465, in open
    response = self._open(req, data)
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 483, in _open
    '_open', req)
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 443, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 1283, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 1243, in do_open
    r = h.getresponse()
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1174, in getresponse
    response.begin()
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 282, in begin
    version, status, reason = self._read_status()
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 251, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response
```

**Comment by mehanig** [comment]
Sorry for long response.
Can't reproduce this problem, that might cause by temporary server problems. Now it's working as expected.

**Comment by vyahhi** [comment]
@mehanig why not to catch http.client.RemoteDisconnected (and other exceptions) and handle it gracefully?

**Comment by mehanig** [comment]
@vyahhi https://github.com/StepicOrg/stepic-oauth2-videodownloader/blob/master/weekDownloader.py#L70 no other operations involved in execution at this line, except for-loop.

Good point, but.
What is expected behavior after we catch the exception? Print fancy Error msg?
I don't see reason why "Error occurred" message is better than regular stack trace. 
Also amount of exceptions possibly raised here is huge. - https://docs.python.org/3/library/http.client.html
and exception `http.client.RemoteDisconnected` was introduced in 3.5 python.
While this is not an app, but a script and example of how to access videos through Stepic Api, for me it's fine to keep things simple.
The only reasonable exception-catching technique here might be allowing to download not all videos, but a slice, from Nth-step to Mth, and trying to re-download after failing with some timeout. But still, not sure if it needs to be implemented

**Comment by vyahhi** [comment]
@mehanig you can catch more general exceptions:

```
http.client.RemoteDisconnected
A subclass of ConnectionResetError and BadStatusLine.
```

> What is expected behavior after we catch the exception? Print fancy Error msg?
> I don't see reason why "Error occurred" message is better than regular stack trace. 

Current solution is not user-friendly, especially for non-Python developers and non-developers. But let's keep it this way for simplicity.
